name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Stop existing Node.js server
            PID=$(sudo lsof -t -i:3000)
            if [ ! -z "$PID" ]; then
              sudo kill -9 $PID
            fi
            
            # Remove previous repository
            rm -rf ShippingFront
            
            # Clone new repository
            git clone https://github.com/Parthvaghela8/ShippingFront.git
            
            # # Install dependencies
            # cd /home/ec2-user/ShippingWars
            # npm install
            
            # Start Node.js server
            nohup node server.js > output.log 2>&1 &
